### ISSUE TITLE
Unable to connect to pushshift.io Error when retrieving submissions at a certain dates

### ISSUE THREAD

**Issue by kevinchua6** [dmarx/psaw#49]
When I attempt to search submissions after 2014, I get an `Unable to connect to pushshift.io` error even though I am able to search it via the URL just fine.

https://api.pushshift.io/reddit/submission/search/?after=1400689570&sort=asc&subreddit=hearthstone

I am sure that my IP is not banned from pushshift as I am able to search other parameters without the date. 

Is the problem with PSAW? Or am I doing something wrong?

``` 
from psaw import PushshiftAPI
api = PushshiftAPI()
submissions = api.search_submissions(
            subreddit='hearthstone',
            limit=2,
            after=1400689570,
            sort='asc')
next(submissions)

UserWarning: Unable to connect to pushshift.io. Retrying after backoff.
  warnings.warn("Unable to connect to pushshift.io. Retrying after backoff.")
Traceback (most recent call last):

  File "<ipython-input-58-40887c187aac>", line 1, in <module>
    next(submissions)

  File "C:\Users\Volition\Anaconda3\lib\site-packages\psaw\PushshiftAPI.py", line 192, in _search
    for response in self._handle_paging(url):

  File "C:\Users\Volition\Anaconda3\lib\site-packages\psaw\PushshiftAPI.py", line 178, in _handle_paging
    yield self._get(url, self.payload)

  File "C:\Users\Volition\Anaconda3\lib\site-packages\psaw\PushshiftAPI.py", line 154, in _get
    self._impose_rate_limit(i)

  File "C:\Users\Volition\Anaconda3\lib\site-packages\psaw\PushshiftAPI.py", line 128, in _impose_rate_limit
    time.sleep(interval)

KeyboardInterrupt
```

**Comment by kevinchua6** [comment]
Closing issue as the api works again now

**Comment by Jiayang-21** [comment]
Experience the same issue, how did you make it work may I ask? Thanks!

**Comment by bybilal** [comment]
Yes im getting same issue, how did you solve this?

**Comment by Jiayang-21** [comment]
I switched to pmaw and it worked like a gem @ByBilal I think psaw is not well-maintained anymore
